name: ronoch_coffee
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  cached_network_image: ^3.3.0
  intl: ^0.18.0
  provider: ^6.0.5
  path_provider: ^2.1.0
  path: ^1.8.3
  awesome_snackbar_content: ^0.1.1
  splash_master: ^0.0.3
  image_picker: ^1.0.7
  
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  url_launcher: ^6.1.14
  webview_flutter: ^4.4.4
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.0
  permission_handler: ^11.0.0
  device_info_plus: ^10.0.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Icons/

  